### PR TITLE
New Winterthur-Data + Choose Dataset in Meta-Config

### PR DESCRIPTION
**Pull request by mwaeckerlin**
Please copy my changes to main branch.

Labels and value selsction is now in meta.json.

In Future, this should be configurable from User-Gui.

I already updated zurich and bern.

### CODE REVIEW

**Comment by tpreusse** [comment]
thanks for the pull request, I'm doing some refactoring and will then merge it

**Comment by mwaeckerlin** [comment]
Please update winterthur.budget.opendata.ch

**Comment by tpreusse** [comment]
deployed app & data

**Comment by mwaeckerlin** [comment]
Am Dienstag, 21. Mai 2013, 14.31:07 schrieb Thomas Preusse:

> deployed app & data

Cool, merci!

Gruss

## Marc

Marc Wäckerlin, Gemeinderat Winterthur, Piratenpartei
marc.waeckerlin@piratenpartei.ch 076/434'11'18
http://winterthur.zh.piratenpartei.ch/profile/mrw

**Pull request merged**
